#define ADAPTER_BUTTON_1  -1
#define ADAPTER_BUTTON_2  -1
#define ADAPTER_RGB_COUNT 1
#define ADAPTER_PORT_COUNT 1

#define ADAPTER_GLOBAL_POLLRATE 8
#define ADAPTER_GLOBAL_LOOPCOUNT 1

#define ADAPTER_MANUFACTURER "HHL"
#define ADAPTER_PRODUCT "LodgeNet"
#define ADAPTER_STRING "LGC"

#define ADAPTER_FIRMWARE_VERSION 0x0001
#define ADAPTER_SETTINGS_VERSION 0x0003
#define ADAPTER_WEBUSB_URL "handheldlegend.github.io/gcp"